// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ultra.Core.WebApi.DAL;

#nullable disable

namespace Ultra.Core.WebApi.DAL.Migrations
{
    [DbContext(typeof(UltraDbContext))]
    [Migration("20230322165753_added_city_to_house")]
    partial class addedcitytohouse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ult_crm")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ultra.Core.DAL.Entities.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SYSTEM_NAME");

                    b.HasKey("Id")
                        .HasName("PK_ENTITY_TYPE");

                    b.ToTable("ENTITY_TYPE", "ult_crm");
                });

            modelBuilder.Entity("Ultra.Core.DAL.Entities.FavoriteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("ENTITY_ID");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ENTITY_TYPE_ID");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_FAVORITE_ENTITY");

                    b.HasIndex("EntityTypeId")
                        .HasDatabaseName("IX_FAVORITE_ENTITY_ENTITY_TYPE_ID");

                    b.ToTable("FAVORITE_ENTITY", "ult_crm");
                });

            modelBuilder.Entity("Ultra.Core.WebApi.DAL.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("integer")
                        .HasColumnName("DELETE_USER_ID");

                    b.Property<int?>("FoundationYear")
                        .HasColumnType("integer")
                        .HasColumnName("FOUNDATION_YEAR");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry")
                        .HasColumnName("LOCATION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("POPULATION");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("UPDATE_USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_CITY");

                    b.ToTable("CITY", "ult_crm");
                });

            modelBuilder.Entity("Ultra.Core.WebApi.DAL.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("ADDRESS");

                    b.Property<int?>("BuildingYear")
                        .HasColumnType("integer")
                        .HasColumnName("BUILDING_YEAR");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("CITY_ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("integer")
                        .HasColumnName("DELETE_USER_ID");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry")
                        .HasColumnName("LOCATION");

                    b.Property<int>("MagicNumber")
                        .HasColumnType("integer")
                        .HasColumnName("MAGIC_NUMBER");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("OWNER_ID");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("UPDATE_USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_HOUSE");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_HOUSE_CITY_ID");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_HOUSE_OWNER_ID");

                    b.ToTable("HOUSE", "ult_crm");
                });

            modelBuilder.Entity("Ultra.Core.WebApi.DAL.Entities.Man", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("AGE");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("ASSIGNED_USER_ID");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("PK_MAN");

                    b.ToTable("MAN", "ult_crm");
                });

            modelBuilder.Entity("Ultra.Core.DAL.Entities.FavoriteItem", b =>
                {
                    b.HasOne("Ultra.Core.DAL.Entities.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FAVORITE_ENTITY_ENTITY_TYPE_ENTITY_TYPE_ID");

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("Ultra.Core.WebApi.DAL.Entities.House", b =>
                {
                    b.HasOne("Ultra.Core.WebApi.DAL.Entities.City", "City")
                        .WithMany("Houses")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_HOUSE_CITY_CITY_ID");

                    b.HasOne("Ultra.Core.WebApi.DAL.Entities.Man", "Owner")
                        .WithMany("Houses")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK_HOUSE_MAN_OWNER_ID");

                    b.Navigation("City");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Ultra.Core.WebApi.DAL.Entities.City", b =>
                {
                    b.Navigation("Houses");
                });

            modelBuilder.Entity("Ultra.Core.WebApi.DAL.Entities.Man", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
