# Project docker compose file to start up postgres.
#
# 1. Set the postgres variables in proj.env
# 2. Update load-extensions.sh to create the extensions you want loaded
# 3. Upon running for the first time, the container will be created and the database initialized
# 4. Subsequent times you run, the database will already be initialized
# 5. Deleting the container removes the content
#
#
#  To run in the foreground (easiest)
#  > docker-compose up
#
#  To run in the background and tail the logs
#  > docker-compose up -d
#  > docker-compose logs -f
#
#  Subsequent builds (if you change pg-Dockerfile)
#  > docker-compose build
#
version: "3.7"
services:
  postgres:
    container_name: ultra_postgres
    build:
      context: .
      dockerfile: postgres-Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ult
      - POSTGRES_USER=postgres
    # You can put all of your env vars in env_file, but you may also only
    # want to put secrets in it and put the file in .gitignore
    env_file:
      - proj.env
    # Uncomment the following if you really want to keep your postgres data around
    # on your disk. This will write to a local directory called 'db-data'
    volumes:
      - c:/docker/volumes/ultra_postgres:/var/lib/postgresql/data
      - ./sql/init_ult_db.sql:/docker-entrypoint-initdb.d/01_init_ult_db.sql
